config:
  wispbit:ai-api-key:
    secure: AAABABoGiCUyI1B6xe7yY99jrhBPPonGLO6onFQWMcygRr+nlnoBzkYal5g3fEa9CTgNkR0lCAO0w49Jx+P1uwjlBApdYq8AERPTIsjw/6KuEkurGb1fGKRQB8G9w0Z1ov2LkJsXshGl
  vercel:team: overdoll
  vercel:apiToken:
    secure: AAABAFGIVDQ6HmmTOSeORDEkBQV/HJC3UavrEQrMzo23Q5YDJRWBkJsJZcKCMziFm3hS4GqB2+I=
  wispbit:clerk-jwt-pem-public-key:
    secure: AAABAJ7yWB87rBVtRKr+hCUwB9vpnKk90G2MD270VRt/EjnAjXhtpWiZTEuMh7jVbD3k9tW5fvYR3t+bm80tFcxlQEY0Fu7CerJXH1aQ91Z5x71r0breUV5TpRklIEv9LcjLbDVxXLnOyDsDy07foBg5t68MYVvZ63GLlV8R+H1HJydDEcEp8sVu+6cT3+fDf1WM28nxYoN6lpWENnXYOefJjHzdlLVjy1Hbyo9fkbeTMIJPg3bPbmOoAzJZi2wumpxQlMO2AaywwnnsSxYpv6Dz7SgWZb6y6yI9nYmUMsu4v/2Z413pDl1V48w5hOYwGV9hj9QrEWfE/3sXwrW5+hiMaV13Jk8JQ0gjYwVTOqdOF4vbLN9JssJYPvzsIDRWu3LeK5CjmJzf9VG8zptiABXr0nLKX86W1LoHHjLE2LIK3v8DGqNOXwkrrwTOkdwtxVt/ZlLC+LGg9+mEbA1ErBotiDWfzYrwYhNzvgbfDVRSlCmjaVe0e2T3uwA3LUM2fhLDQNapIOg4Ky8+YO4rb5FDy0AcvjQ4ZnLT6bE7F7HgfPvSdJ1/XtAIokEZ/wCQBEi1znwkKfJE9a5AdIQEOejPXKu5HDfGnfNms1urZwyDdr5DJxmYAfr0bqq+ULoRS8sQm1Ol4XRkPP8HVYZch1n6+jPhXHpQJO3qr0hqc9o0SqdaQs2mXl+aWaBg40mU8wdhTIKviL2lvhBjrhsoVDTAg0xVdhKvLLrCgTg5ypApF2ANDmLAKksgsLJypqhkR3fTpWGFVDBV1lYFkEQ43OkDYPWkBIeu2yZH9c2O6FNQwm4KRtLBlZzRIIHU2yZR6u/Tex6HI/ckAfTt
  wispbit:clerk-jwt-jwks-url:
    secure: AAABADs3vJkfpChccaIyPCyMrHTkzoBwypoEaLd3jErx2HC1ynDwbPoqNXe59nW8tTiB00/HrSZlu7p0x4jOAP1IRRrBfRbAMwAkhuhWJQ==
  wispbit:clerk-publishable-key:
    secure: AAABAGvKOEYBlaGxyR6prgMeBHZPJDvyP6Hxkp7g1fiA/tv+LbTcmcLmlj/J2XQJsIt6GnJhvAEIpYiMDU3MLQ==
  wispbit:clerk-secret-key:
    secure: AAABAG8Nj4k8+u+pd+pXQg/xJO85WAEybiAgpW575zwDHEP21qg/Eysg8rTmZJXNzwFN3ehRBZq0InAPJ9jxo7hXaSRuWsUFTwPQVJTdirEdaQ==
  aws:region: us-east-1
  aws:profile: overdoll
  cloudflare:apiToken:
    secure: AAABACTyBCdsmqBzgJAFDtr82k9dg6v3Cvr/HJmTr2vRZdfh5owAEGRhvBDvJGdMoV2nN9Y/g7+ioCrHJ7L3vEo8HakNpC+J
  wispbit:cloudflare-account-id:
    secure: AAABACoEgLzOsGbrfPUryZlm4ZekIi2x/kVyry81TTWOk1kPYXWgRLQi/qZTFoCC5csUgP5w0b05dfKDqSbwJA==
  wispbit:sentry-dsn-backend:
    secure: AAABADbvPU9dvOxiEsIKBk9aZn3KF3LelG0XpQ1nS4ziZ3a3xgpoftZ4AcqacHiFb65y6rno183yHR0RbOoBPF4YQ1qY0twJhqRyv9e/OH/7OGQkyQQQ8g/82488x1/j844CvUy/K+7uZo8I7kgnPwrRvnsbO/07DdHNh72/EQ==
  wispbit:sentry-dsn-frontend:
    secure: AAABAHvceSKWDJtT+hSOYW+ZO1OkXrB7yqpZmPaydy6zE7PX8di+IGTbiN+ZC0X4xU8hYQoYiiakGGLYJwzMXVwqRcGtFz5Y+nEzEHt06/XHERA090u5RNKDOwb5LSkMZyjx6np+Wkphtbmiq6LV2U9ksi2O6evHDoFIsc1YAw==
  wispbit:posthog-key:
    secure: AAABAE9Qv51nyGSOGl8o/ZVfc4TET7c4mnKHn/Z3xUlsfu4KD4ILlKqQctP0KbkZMjCVQnvmz1I8HWv87qzg/iT0PIa5L0htWZ8sCOXXPw==
  wispbit:loops-api-key:
    secure: AAABANU7o/ilO+dtwGkp3tpymfO2Z+xSlilyk5A4lKJ1ZuZ5perzdJNZIGYzWInvD/EOX0TwJdPjgK9inppSWQ==
